const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
const { globSync } = require("glob");

const jsYamlForMatter = require(
  require.resolve("js-yaml", { paths: [require.resolve("gray-matter")] }),
);

const matterOptions = {
  engines: {
    yaml: {
      parse: (value) => jsYamlForMatter.load(value.replace(/\\\|/g, "|")),
      stringify: (value) => jsYamlForMatter.dump(value),
    },
  },
};

const DEFAULT_SITE_BASE_URL = "https://luwiki.pages.dev";
const GENERATED_MARKER =
  "<!-- Generated by the luwiki build. Do not edit this file directly. -->";

function normalizeBaseUrl(value) {
  let baseUrl = String(value || DEFAULT_SITE_BASE_URL).trim();
  if (!/^https?:\/\//i.test(baseUrl)) {
    baseUrl = `https://${baseUrl}`;
  }
  return baseUrl.replace(/\/+$/, "");
}

function normalizeRoute(value) {
  let route = String(value || "/").trim();
  if (!route.startsWith("/")) {
    route = `/${route}`;
  }
  route = route.split("#", 1)[0].split("?", 1)[0];
  route = path.posix.normalize(route);
  if (!route.endsWith("/")) {
    route += "/";
  }
  return route;
}

function pageCompanionRoute(route) {
  const normalized = normalizeRoute(route);
  return normalized === "/" ? "/llm.txt" : `${normalized}llm.txt`;
}

function absoluteUrl(route, baseUrl) {
  const safeRoute = String(route || "").replace(/%(?![0-9a-f]{2})/gi, "%25");
  return new URL(safeRoute, `${normalizeBaseUrl(baseUrl)}/`)
    .href.replace(/\(/g, "%28")
    .replace(/\)/g, "%29");
}

function tagsFor(data) {
  const tags = Array.isArray(data.tags)
    ? data.tags
    : data.tags
      ? [data.tags]
      : [];
  return tags.map(String);
}

function loadPublishedNotes(sourceDir, baseUrl) {
  const notes = globSync("**/*.md", {
    cwd: sourceDir,
    absolute: true,
    nodir: true,
  })
    .map((filePath) => {
      const parsed = matter(fs.readFileSync(filePath, "utf8"), matterOptions);
      const data = parsed.data || {};
      if (data.hide === true || data["dg-publish"] === false) {
        return null;
      }

      const fileName = path.basename(filePath, path.extname(filePath));
      const title = String(data.title || fileName).trim();
      const tags = tagsFor(data);
      const route = tags.includes("gardenEntry")
        ? "/"
        : normalizeRoute(data.permalink || `/notes/${fileName}/`);
      const companionRoute = pageCompanionRoute(route);

      return {
        filePath,
        fileName,
        title,
        tags,
        aliases: Array.isArray(data.aliases) ? data.aliases.map(String) : [],
        created: data.created ? String(data.created) : "",
        updated: data.updated ? String(data.updated) : "",
        route,
        canonicalUrl: absoluteUrl(route, baseUrl),
        companionRoute,
        companionUrl: absoluteUrl(companionRoute, baseUrl),
        source: parsed.content.trim(),
      };
    })
    .filter(Boolean)
    .sort(
      (left, right) =>
        left.title.localeCompare(right.title, "zh-CN", {
          numeric: true,
          sensitivity: "base",
        }) || left.route.localeCompare(right.route),
    );

  const routes = new Set();
  for (const note of notes) {
    if (routes.has(note.companionRoute)) {
      throw new Error(`Duplicate LLM companion route: ${note.companionRoute}`);
    }
    routes.add(note.companionRoute);
  }

  return notes;
}

function aliasKey(value) {
  return String(value || "")
    .replace(/\\\|/g, "|")
    .replace(/\.md$/i, "")
    .trim()
    .normalize("NFC")
    .toLocaleLowerCase("zh-CN");
}

function buildAliasMap(notes) {
  const aliases = new Map();
  const register = (value, note) => {
    const key = aliasKey(value);
    if (!key) return;
    const existing = aliases.get(key);
    if (existing && existing.route !== note.route) {
      aliases.set(key, null);
      return;
    }
    if (!aliases.has(key)) {
      aliases.set(key, note);
    }
  };

  for (const note of notes) {
    register(note.fileName, note);
    register(note.title, note);
    for (const alias of note.aliases) register(alias, note);
  }
  return aliases;
}

function escapeMarkdownText(value) {
  return String(value || "")
    .replace(/\\/g, "\\\\")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/\s+/g, " ")
    .trim();
}

function resolveWikiTarget(target, aliases) {
  const withoutHeading = target.split("#", 1)[0].trim();
  const candidates = [
    withoutHeading,
    path.posix.basename(withoutHeading),
  ];
  for (const candidate of candidates) {
    const note = aliases.get(aliasKey(candidate));
    if (note) return note;
  }
  return null;
}

function convertPageSource(note, aliases, baseUrl) {
  let content = note.source.replace(/\r\n?/g, "\n");

  content = content.replace(/!\[\[([^\]]+)\]\]/g, (_match, value) => {
    const normalized = value.replace(/\\\|/g, "|");
    const [target, label] = normalized.split("|", 2);
    return `图片：${escapeMarkdownText(label || target.split("#", 1)[0])}`;
  });

  content = content.replace(/\[\[([^\]]+)\]\]/g, (_match, value) => {
    const normalized = value.replace(/\\\|/g, "|");
    const [target, label] = normalized.split("|", 2);
    const linkText = escapeMarkdownText(label || target.split("#", 1)[0]);
    const targetNote = resolveWikiTarget(target, aliases);
    return targetNote
      ? `[${linkText}](${absoluteUrl(targetNote.companionRoute, baseUrl)})`
      : linkText;
  });

  content = content.replace(
    /!\[([^\]]*)\]\(([^)\n]+)\)/g,
    (_match, alt) => (alt.trim() ? `图片：${escapeMarkdownText(alt)}` : ""),
  );

  content = content.replace(
    /\[([^\]]+)\]\(([^)\n]+)\)/g,
    (match, label, hrefWithTitle) => {
      const href = hrefWithTitle.trim().split(/\s+"/, 1)[0].replace(/^<|>$/g, "");
      const normalizedHref = href.replace(/^(?:\.\.\/|\.\/)+/, "");
      if (/^\/?raw\//i.test(normalizedHref)) {
        return escapeMarkdownText(label);
      }
      if (href.startsWith("/")) {
        return `[${escapeMarkdownText(label)}](${absoluteUrl(href, baseUrl)})`;
      }
      return match;
    },
  );

  const lines = content.trim().split("\n");
  const firstContentLine = lines.findIndex((line) => line.trim());
  if (firstContentLine >= 0) {
    const heading = lines[firstContentLine].match(/^#\s+(.+)$/);
    if (heading && aliasKey(heading[1]) === aliasKey(note.title)) {
      lines.splice(firstContentLine, 1);
      while (lines[firstContentLine] !== undefined && !lines[firstContentLine].trim()) {
        lines.splice(firstContentLine, 1);
      }
    }
  }

  return lines.join("\n").trim();
}

function renderPageCompanion(note, aliases, baseUrl) {
  const metadata = [
    `- 规范页面：[${escapeMarkdownText(note.title)}](${note.canonicalUrl})`,
    `- 本页 LLM 文本：${note.companionUrl}`,
  ];
  if (note.updated) metadata.push(`- 更新日期：${note.updated}`);
  if (note.created) metadata.push(`- 创建日期：${note.created}`);
  const publicTags = note.tags.filter(
    (tag) => tag !== "gardenEntry" && tag !== "note",
  );
  if (publicTags.length) metadata.push(`- 标签：${publicTags.join("、")}`);

  return [
    GENERATED_MARKER,
    `# ${note.title}`,
    "",
    "> 噜Wiki 页面级 LLM companion；由公开页面在构建时自动生成。",
    "",
    ...metadata,
    "",
    "## 正文",
    "",
    convertPageSource(note, aliases, baseUrl),
    "",
  ].join("\n");
}

function renderSiteIndex(notes, baseUrl, siteName) {
  const lines = notes.map((note) => {
    const publicTags = note.tags.filter(
      (tag) => tag !== "gardenEntry" && tag !== "note",
    );
    const suffix = publicTags.length ? `：标签 ${publicTags.join("、")}` : "";
    return `- [${escapeMarkdownText(note.title)}](${note.companionUrl})${suffix}`;
  });

  return [
    GENERATED_MARKER,
    `# ${siteName}`,
    "",
    `> 噜Wiki 的全站 LLM 索引；当前包含 ${notes.length} 个公开页面。每个链接指向该页面自动生成的 llm.txt。`,
    "",
    `- 站点：${normalizeBaseUrl(baseUrl)}/`,
    "- 说明：页面增删会在下一次构建时自动同步到本索引及页面级 companion。",
    "",
    "## 全部公开页面",
    "",
    ...lines,
    "",
  ].join("\n");
}

function outputPathForRoute(outputDir, route) {
  const root = path.resolve(outputDir);
  const pathname = String(route || "")
    .split("#", 1)[0]
    .split("?", 1)[0];
  const relative = pathname.replace(/^\/+/, "");
  const target = path.resolve(root, relative);
  if (target !== root && !target.startsWith(`${root}${path.sep}`)) {
    throw new Error(`Unsafe LLM output route: ${route}`);
  }
  return target;
}

function writeText(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
}

function removeStaleCompanions(outputDir, expectedPaths) {
  for (const filePath of globSync("**/llm.txt", {
    cwd: outputDir,
    absolute: true,
    nodir: true,
  })) {
    const resolved = path.resolve(filePath);
    if (expectedPaths.has(resolved)) continue;
    const content = fs.readFileSync(filePath, "utf8");
    if (content.startsWith(GENERATED_MARKER)) {
      fs.unlinkSync(filePath);
    }
  }
}

function generateLlmsArtifacts({
  sourceDir = "src/site/notes",
  outputDir = "dist",
  siteBaseUrl = process.env.SITE_BASE_URL || DEFAULT_SITE_BASE_URL,
  siteName,
} = {}) {
  const baseUrl = normalizeBaseUrl(siteBaseUrl);
  const notes = loadPublishedNotes(sourceDir, baseUrl);
  const aliases = buildAliasMap(notes);
  const expectedPaths = new Set();

  for (const note of notes) {
    const outputPath = outputPathForRoute(outputDir, note.companionRoute);
    expectedPaths.add(outputPath);
    writeText(outputPath, renderPageCompanion(note, aliases, baseUrl));
  }

  removeStaleCompanions(outputDir, expectedPaths);

  const gardenEntry = notes.find((note) => note.tags.includes("gardenEntry"));
  writeText(
    path.join(outputDir, "llms.txt"),
    renderSiteIndex(notes, baseUrl, siteName || gardenEntry?.title || "噜Wiki"),
  );

  return {
    pageCount: notes.length,
    indexPath: path.join(outputDir, "llms.txt"),
    companionPaths: [...expectedPaths],
  };
}

module.exports = {
  DEFAULT_SITE_BASE_URL,
  generateLlmsArtifacts,
  loadPublishedNotes,
  pageCompanionRoute,
};
